import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../../public/assets/style/style.css";
import "../../public/assets/style/mystyle.scss";
import ClientWrapper from "./ClientWrapper";
import { Toaster } from "@/components/ui/toaster"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Praveen's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/img/logo.png", // ✅ PNG as favicon
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientWrapper>
          {children}
          <Toaster />

        </ClientWrapper>
      </body>
    </html>
  );
}
