import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../../public/assets/style/style.css"
import "../../public/assets/style/mystyle.scss"
import Footer from "./components/Footer";
import Header from "./components/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Praveen's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/img/logo.png", // ✅ PNG as favicon
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <Header />

        {children}

        <Footer/>

      </body>
    </html>
  );
}
